name: learn_feeds_assignment_onloop
description: Onloop learn feed

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

# Styles
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

# Network
  dio: ^4.0.3

# Design pattern
  flutter_bloc: ^7.3.3

# Localization
  intl: ^0.17.0

# Database
  shared_preferences: ^2.0.8

# Other
  equatable: ^2.0.3
  flutter_webview_plugin: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/


